from flask import Blueprint, jsonify, request
from flask_login import login_required, current_user
from app import db
from app.models.leave import LeaveRequest
from app.models.attendance import Attendance
from app.models.user import User
from app.services.qr_service import validate_qr_code
from app.utils.decorators import role_required
from datetime import datetime
from sqlalchemy import func

qr_bp = Blueprint('qr', __name__, url_prefix='/qr')

@qr_bp.route('/scan', methods=['POST'])
@login_required
@role_required(['warden', 'admin'])
def scan_qr():
    try:
        data = request.get_json()
        qr_code = data.get('qr_code')
        today = datetime.today().date()
        
        # 1. Validate QR code
        leave_id = validate_qr_code(qr_code)
        if not leave_id:
            return jsonify({
                'success': False, 
                'message': 'Invalid QR code format. This QR code was not generated by our system.'
            }), 200
        
        # 2. Fetch leave and check approval status
        leave = LeaveRequest.query.get(leave_id)
        if not leave:
            return jsonify({
                'success': False, 
                'message': f'Leave request #{leave_id} not found. It may have been deleted.'
            }), 200
        if leave.status != 'approved':
            return jsonify({
                'success': False, 
                'message': f'This leave request is {leave.status}. Only approved leaves can be scanned.'
            }), 200
        if not (leave.start_date <= today <= leave.end_date):
            return jsonify({
                'success': False, 
                'message': f'This leave is not valid today. Valid period: {leave.start_date.strftime("%d-%m-%Y")} to {leave.end_date.strftime("%d-%m-%Y")}'
            }), 200

        # 3. Get attendance scan history for this leave
        scans = Attendance.query.filter_by(
            leave_id=leave_id,
            student_id=leave.student_id
        ).order_by(Attendance.timestamp.asc()).all()

        # 4. Decide what scan is allowed
        scan_type = None
        if not scans:
            scan_type = 'exit'  # First scan must be exit
        elif len(scans) == 1 and scans[0].scan_type == 'exit':
            scan_type = 'entry'  # Second scan must be entry
        else:
            return jsonify({
                'success': False,
                'message': 'QR code already fully used! Entry and exit recorded for this leave.'
            }), 200

        # Prevent repeated scan of same type on the same day
        if scans and scans[-1].scan_type == scan_type and scans[-1].timestamp.date() == today:
            return jsonify({
                'success': False,
                'message': f"This {scan_type.upper()} has already been recorded today."
            }), 200

        # 5. Record attendance
        attendance = Attendance(
            student_id=leave.student_id,
            leave_id=leave_id,
            scan_type=scan_type,
            scanned_by=current_user.id,
            location='Main Gate'
        )
        db.session.add(attendance)
        db.session.commit()

        # 6. Return result
        student = leave.student
        return jsonify({
            'success': True,
            'message': f'{scan_type.upper()} recorded successfully.',
            'leave_id': leave_id,
            'student_id': student.id,
            'student_name': student.name,
            'student_contact': f'{student.phone} / {student.email}',
            'student_profile_image': student.profile_image,
            'leave_dates': f"{leave.start_date.strftime('%B %d, %Y')} to {leave.end_date.strftime('%B %d, %Y')}",
            'leave_days': (leave.end_date - leave.start_date).days + 1,
            'scan_type': scan_type,
            'timestamp': attendance.timestamp.strftime('%Y-%m-%d %I:%M:%S %p')
        }), 200
    except Exception as e:
        import traceback; traceback.print_exc()
        return jsonify({'success': False, 'message': 'Internal error: ' + str(e)}), 500


@qr_bp.route('/generate/<int:leave_id>')
@login_required
def generate_qr(leave_id):
    leave = LeaveRequest.query.get_or_404(leave_id)
    
    # Check permission - students can only view their own QR codes
    if current_user.role == 'student' and leave.student_id != current_user.id:
        return jsonify({'error': 'Unauthorized'}), 403
    
    # Check if leave is approved
    if leave.status != 'approved':
        return jsonify({'error': 'Leave must be approved to generate QR code'}), 400
    
    # Generate QR code if not already exists
    if not leave.qr_code:
        from app.services.qr_service import generate_qr_code
        leave.qr_code = generate_qr_code(leave_id)
        db.session.commit()
    
    return jsonify({
        'success': True,
        'qr_code': leave.qr_code,
        'leave_id': leave_id,
        'student_name': leave.student.name,
        'valid_from': leave.start_date.strftime('%Y-%m-%d'),
        'valid_to': leave.end_date.strftime('%Y-%m-%d')
    })

@qr_bp.route('/validate/<int:leave_id>')
@login_required
@role_required(['warden', 'admin'])
def validate_leave_qr(leave_id):
    """Validate if a leave QR code is currently valid"""
    leave = LeaveRequest.query.get_or_404(leave_id)
    today = datetime.today().date()
    
    is_valid = (
        leave.status == 'approved' and
        leave.start_date <= today <= leave.end_date
    )
    
    # Get today's scans
    today_scans = Attendance.query.filter_by(
        leave_id=leave_id,
        student_id=leave.student_id
    ).filter(
        func.date(Attendance.timestamp) == today
    ).all()
    
    return jsonify({
        'valid': is_valid,
        'leave_id': leave_id,
        'student_name': leave.student.name,
        'status': leave.status,
        'valid_dates': f"{leave.start_date} to {leave.end_date}",
        'today_scans': [{
            'time': scan.timestamp.strftime('%H:%M:%S'),
            'type': scan.scan_type,
            'location': scan.location
        } for scan in today_scans]
    })

# Test endpoint to check if QR routes are working
@qr_bp.route('/test')
def test_qr():
    return jsonify({'status': 'QR routes working'})
